name: projet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.1
  get: ^4.6.6
  http: ^1.2.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # The following line ensures that the Material Icons font is included with your application
  uses-material-design: true

  # Define your assets here
  assets:
    - assets/orange_dog.png
    - assets/blue_dog.png
    - assets/red_dog.png
    - assets/yellow_dog.png
    - assets/white_dog.png
    - assets/wiggle_logo.png
    - assets/owner.png
